import React from 'react';
import styles from './tnc.module.scss';
import { WebsiteLayout } from '../../layouts';
import { organization } from '../../constants';

export default function TermsAndCondtions() {
  return (
    <WebsiteLayout>
      <h1>General Terms and Conditions</h1>
      <h2>1. Introduction</h2>
      <p>These provisions govern the use of the <a href={`http://${organization.website}`}>{organization.website}</a> web site (hereinafter, the “<b>Web Site</b>” or the “<b>Portal</b>”), as well as the use of the services offered by {organization.registeredName} (“<b>{organization.shortName}</b>”) through the site.</p>
      <p>By accessing to the Web Site or, as the case may be, when accepting the present General Conditions, you (hereinafter, the &#8220;<b>Client</b>&#8220;) confirm that you have read and agree to these conditions and, in consequence, you start a legal relationship with {organization.shortName} in accordance with its provisions.</p>
      <p>Registration within the Portal and the use of its services implies that your data as a Client will be included in {organization.shortName} files and will be processed in accordance with the provisions of the <a href={`https://${organization.website}/privacy-policy`}>Privacy Policy</a>, which the Client expressly states that he/she understands and accepts.</p>
      <p>The General Conditions included will be the conditions in force at the relevant moment.</p>
      <p>The access to the Web Site is free, except as regards the cost of connection via the telecommunications network provided by the supplier contracted by the Client.</p>
      <h2>2. Contracting the services</h2>
      <p>The access and contracting process and the terms and conditions of the provision of the services by {organization.shortName} will be subject at all times to the provisions set out on the Portal.</p>
      <p>Likewise, the Client, when contracting the provision of services, expressly undertakes to supply true and licit information in this regard, and assumes for these purposes any damages caused directly or indirectly to {organization.shortName} and/or to any third party arising from from the lack of truthfulness or the illicit nature of the data supplied by him/her.</p>
      <h2>3. Intellectual Property Rights</h2>
      <p>{organization.shortName} is the owner of the domain {organization.website}</p>
      <p>All exploitation rights are reserved.</p>
      <p>This Website is protected by legislation on intellectual and industrial property.</p>
      <p>The Portal, in its entirely, including without any exceptions, its design, structure and distribution, text and contents, logos, buttons, images, source code, as well as the intellectual and industrial property rights and any other distinctive sign related to the aforementioned, to the Web Site itself, and any other that appears on the website, as well as all those related to the services offered by {organization.shortName} and those owned by {organization.shortName}, are subject to intellectual and industrial property rights by {organization.shortName} and/or third parties who have authorized their inclusion in the Website.<br />
        Therefore, it is prohibited to, by means, their use, exploitation, copy, reproduction, as well as their elimination, damage, and/or modification, registration and/or request of registration them, partially or totally, temporarily or permanently, and any other similar presently or in the future without the {organization.shortName}&#8217;s express and written authorization, and/or of the corresponding owner, without the possibility to understand that exists a license or authorization whatever its nature, total and/or partial, to any third parties and/or client by {organization.shortName} and/or from the corresponding owner.<br />
        {organization.shortName} reserves the right to unilaterally redesign and modify, in any moment, and without further notice, the presentation and configuration of the Web Site.</p>
      <p>The client will abstain, in every case, from deleting, altering, avoiding or manipulating any security device or security system that may be installed on the Portal.</p>
      <h2>4. Limitation of Liability</h2>
      <p>There is no relationship or association of any kind between {organization.shortName} and the owners of the websites linked to, therefore, {organization.shortName} is not responsible for third-party websites, neither their utility, trustworthiness, accuracy, nor for the contents included in such sites; they are websites that belong to independent corporations without existing association or relationship. {organization.shortName} is not responsible for any harm and/or damage and/or losses of profit of the Client or of a third party who is damaged by the opinions, representations, data and/or content that, in this case, can be emitted directly or indirectly the Clients and/or third parties for any reason, any time and any by any mean on the Portal.</p>
      <p>{organization.shortName} does not ensure the continuous, reliable, permanent operation of the Web Site, without a delay or interruption; therefore, {organization.shortName} is not responsible for any damage and/or harm and/or loss of profit these may cause for the Client or a third party.</p>
      <p>{organization.shortName} is not responsible for any damage and/or loss of profit for the Client or a third party as a consequence of a circumstance of force majeure, fortuitous event, failure or error in the communications lines, or for the defective rendered service or failure of the Internet.</p>
      <p>{organization.shortName} is not responsible for any damage and/or loss of profit for the Client or a third party as a consequence of a circumstance of force majeure, fortuitous event, failure or error in the communications lines, or for the defective rendered service or failure of the Internet.</p>
      <p>{organization.shortName} is not responsible for any harm and/or damage caused to any Client or third party, neither for harm and/or damages suffered by any Client or third party, caused directly or indirectly by the use and/or access and/or connection to the Portal and/or other linked websites, not being {organization.shortName} responsible for any harm or damage caused to a Client or third party due to incorrect operation, defects, errors or damage caused, totally or partially, to any hardware or software, as well as the loss/alteration and/or damage to the information stored in magnetic supports, disks, tapes, floppy disks and others, as well as the introduction of computer viruses or undesired variations or alterations on the information, documents, files, databases, hardware and/or software.<br />
      {organization.shortName} is not responsible for any harm and/or damage caused to the Client that is not imputable solely, directly and exclusively, to a wilful or negligent action or omission by the company, when the Client and/or a third party or the people who they have to respond to are guilty of this harm and/or damage, or of any harm/damage caused to third parties and/or any loss of profit or benefits suffered by the Client and/or third parties. The links that {organization.shortName} offers the Client have the purpose of making the search of available information on the Internet. {organization.shortName} cannot ensure that the system is adequate for any services outside of the one hired neither that it provides access to all sites on the Internet. {organization.shortName} does not offer nor commercialize the services available in the linked sites, nor does it assume any responsibility for these products or services.</p>
      <p>The links that {organization.shortName} offers the Client have the purpose of making the search of available information on the Internet. {organization.shortName} cannot ensure that the system is adequate for any services outside of the one hired neither that it provides access to all sites on the Internet. {organization.shortName} does not offer nor commercialize the services available in the linked sites, nor does it assume any responsibility for these products or services.</p>
      <p>{organization.shortName} does not control the use of the services made by the Client. In this sense, {organization.shortName} is not responsible for the use and/or the content that, in violation of the law and/or these Terms and Conditions and/or the applicable Particular Terms and Conditions, the Client may make. {organization.shortName} is not responsible for the content and/or information and/or data transmitted, neither originating the transmission, not modifying the data, neither selecting it nor the addressee, being, therefore, the Client the only person responsible for the consequences his/her unlawful use or the use in disagreement with these Terms and Conditions can have, as well as the truthfulness and/or lawfulness of the contents provided by the Client. To these effects, the Client has the obligation to use the services according to the applicable law.</p>
      <p>In the event that {organization.shortName} is aware, by any means, directly or indirectly, of the existence of contents that may infringe on the current laws or these Terms and Conditions and/or the applicable Particular Terms and Conditions, or of the unlawful, unauthorized or fraudulent use, {organization.shortName} is entitled to suspend the services, totally or partially, without the Client’s prior authorisation, by eliminating the infringing contents or taking any other measures considered necessary to disallow the continuity in the infringement detected.<br />
        Without prejudice of the above, {organization.shortName} shall be entitled to communicate to the administrative or judicial authorities the acts that may constitute an illegal activity, without notification to the Client.</p>
      <p>Specifically, {organization.shortName} is not responsible for the defective provision or interruption of the services commercialized and provided in the following events:</p>
      <ul>
        <li>Interruption of the services due to network maintenance.</li>
        <li>Discontinuity in the service caused by the introduction from the client and/or any third parties of hardware or software components that cause a defective operation of the technical systems or that are incompatible with the elements of the system.</li>
        <li>Interruption of the services due to the inability of access to the broadband support.</li>
        <li>Interruption of the services due to an incorrect use or their inadequacy.</li>
        <li>Interruption of the services due to the errors in the electrical power supply to the equipment and devices used by the client to access the services.</li>
        <li>Causes attributable to a third party or force majeure.</li>
        <li>Lost of quality of the service or connection capacity, for causes not directly attributable to {organization.shortName}.</li>
        <li>Administrative or judicial resolutions.</li>
        <li>Incorrect configuration of the necessary installation by people not related to {organization.shortName} and/or by the client and/or any third parties.</li>
        <li>Harm and/or damages that cannot be attributed solely, directly nor exclusively, to {organization.shortName}.</li>
        <li>Lost of profit for the client and/or any third parties.</li>
        <li>Harm and/or damages, of any kind, arising from client and/or a third parties fault.</li>
        <li>Harm and/or damages caused directly or indirectly to the client and/or to any third parties by not directly causes attributable to {organization.shortName}.</li>
      </ul>
      <p>The unpredictable events, as well as the force majeure cases, official measures, errors in the telecommunications connections not directly attributable to {organization.shortName}, will exempt {organization.shortName} from providing services while the unpredictable events, etc., last.</p>
      <h2>5. Confidentiality</h2>
      <p>{organization.shortName}, as well as its personnel and technical support will process and keep the entire Client’s information they have access to while they are carrying out their job duties. They will not use it, divulge it or allow it to be used or divulged by unauthorized third parties. This confidentiality obligation subsists even after {organization.shortName} employees have finished their working relationship with {organization.shortName}.</p>
      <h2>6. Applicable law and Jurisdiction</h2>
      <p>All the discrepancies, claims and controversies that may arise shall be settled by competent courts according to the applicable legislation.</p>
      <p>The present General Conditions are governed and interpreted in accordance with Spanish law.</p>
      <p>The present General Terms and Conditions shall be effective in March 2022.</p>
    </WebsiteLayout>
  )
}
